name: Docker Image CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image with tag
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: cr.yandex/${{ secret.MY_REPOSITORY_ID }}/nginx:${{ github.ref_name }}
    - name: Build and push Docker image with latest
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: cr.yandex/${{ secrets.MY_REPOSITORY_ID }}/nginx:latest

     - name: Update Deployment YAML
      run: |
        sed -i "s/<repository_id>/${{ secrets.MY_REGISTRY_ID }}/g" deployment.yaml
