name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Show secrets
        run: |
          echo ${{ secrets.TF_VAR_access_key }}
          echo ${{ secrets.TF_VAR_secret_key }}
