name: Use Secret from Another Repo

on:
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Get secret from source repo
        id: get-secret
        run: |
          SECRET_VALUE=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/LexionN/devops-diplom/actions/secrets/TF_VAR_DEFAULT_ZONE)
          echo "SECRET_VALUE=$(echo $SECRET_VALUE | jq -r .value)" >> $GITHUB_ENV

      - name: Use the secret
        run: |
          echo "Using secret: ${{ env.SECRET_VALUE }}"
