name: Deploy to Kubernetes

on: workflow_dispatch
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup GitHub Token
      run: |
        git config --global credential.helper 'store --file ~/.git-credentials'
        echo "https://${{ secrets.TOKEN }}:@github.com" > ~/.git-credentials
    
    - name: Checkout diplom-devops repo
      uses: actions/checkout@v2
      with:
        repository: 'LexionN/devops-diplom'
        path: 'devops-diplom'

    - name: Setup kubeconfig
      run: |
        echo "${{ secrets.TF_VAR_DEFAULT_ZONE }}"
