name: Transfer Secrets

on:
  workflow_dispatch:

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Login to GitHub
        env:
          PAT: ${{ secrets.TOKEN }}  # Ваш токен доступа
        run: |
          echo "$PAT" | gh auth login --with-token

      - name: Set secret in another repository
        run: |
          gh secret set TF_VAR_DEFAULT_ZONE --body "your_secret_value" --repo LexionN/devops-diplom
          
