name: Use Secret from Another Repo

on:
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Get secret from source repo
        id: get-secret
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/LexionN/devops-diplom/actions/secrets/TF_VAR_FOLDER_ID)

          if [[ $(echo "$RESPONSE" | jq -r .message) == "Not Found" ]]; then
            echo "Secret not found or insufficient permissions."
            exit 1
          fi

          SECRET_VALUE=$(echo "$RESPONSE" | jq -r .value)
          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV

      - name: Use the secret
        run: |
          echo "Using secret: ${{ env.SECRET_VALUE }}"
