name: Deploy to Kubernetes

on: workflow_dispatch
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GitHub Token
      run: |
        git config --global credential.helper 'store --file ~/.git-credentials'
        echo "https://${{ secrets.TOKEN }}:@github.com" > ~/.git-credentials
    
    - name: Checkout diplom-devops repo
      uses: actions/checkout@v2
      with:
        repository: 'LexionN/devops-diplom'
        path: 'devops-diplom'

    - name: Get secret from devops-diplom
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Ваш токен доступа
      run: |
        SECRET_NAME="TF_VAR_DEFAULT_ZONE"
        SECRET_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                         -H "Accept: application/vnd.github.v3.raw" \
                         "https://api.github.com/repos/LexionN/devops-diplom/actions/secrets/$SECRET_NAME")

        echo "Secret value is: $SECRET_DATA"
