name: Transfer Secret

on:
  workflow_dispatch:

jobs:
  transfer-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: owner/source-repo
          token: ${{ secrets.TOKEN }}

      - name: Get secret from source repo
        id: get-secret
        run: |
          SECRET_VALUE=$(gh secret get TF_VAR_DEFAULT_ZONE --repo LexionN/devops-diplom)
          echo "SECRET_VALUE=${SECRET_VALUE}" >> $GITHUB_ENV

